name: Add mask
on: push
jobs:
    mask:
        runs-on: ubuntu-latest
        env:
            PASSWORD: Super sercret value
        steps:
            - run: echo "::add-mask::${PASSWORD}"
            - run: echo "${PASSWORD}"