name: Dump
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: ./.github/actions/dump
        id: dump_var
        with:
          enable-context: 'true'
      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump_var.outputs.dumpted-date }}