name: GITHUB_OUTPUT
on: push
jobs:
  share:
    runs-on: ubuntue-latest
    steps:
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{ steps.source.outputs.result }}
        run: echo"${RESULT}"
