name: Job summaries
on: push
jobs:
    markdown:
        runs-on: ubuntu-latest
        steps:
            - run: echo "## Example title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
            - run: echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
            - run: echo "- second line" >> "${GITHUB_STEP_SUMMARY}"